// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: nullable.proto

package nullablepb

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullableDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ValueOrNull:
	//
	//	*NullableDate_DateValue
	//	*NullableDate_NullValue
	ValueOrNull isNullableDate_ValueOrNull `protobuf_oneof:"value_or_null"`
}

func (x *NullableDate) Reset() {
	*x = NullableDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nullable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableDate) ProtoMessage() {}

func (x *NullableDate) ProtoReflect() protoreflect.Message {
	mi := &file_nullable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableDate.ProtoReflect.Descriptor instead.
func (*NullableDate) Descriptor() ([]byte, []int) {
	return file_nullable_proto_rawDescGZIP(), []int{0}
}

func (m *NullableDate) GetValueOrNull() isNullableDate_ValueOrNull {
	if m != nil {
		return m.ValueOrNull
	}
	return nil
}

func (x *NullableDate) GetDateValue() *timestamppb.Timestamp {
	if x, ok := x.GetValueOrNull().(*NullableDate_DateValue); ok {
		return x.DateValue
	}
	return nil
}

func (x *NullableDate) GetNullValue() structpb.NullValue {
	if x, ok := x.GetValueOrNull().(*NullableDate_NullValue); ok {
		return x.NullValue
	}
	return structpb.NullValue(0)
}

type isNullableDate_ValueOrNull interface {
	isNullableDate_ValueOrNull()
}

type NullableDate_DateValue struct {
	DateValue *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date_value,json=dateValue,proto3,oneof"`
}

type NullableDate_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,2,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

func (*NullableDate_DateValue) isNullableDate_ValueOrNull() {}

func (*NullableDate_NullValue) isNullableDate_ValueOrNull() {}

type NullableBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ValueOrNull:
	//
	//	*NullableBool_BoolValue
	//	*NullableBool_NullValue
	ValueOrNull isNullableBool_ValueOrNull `protobuf_oneof:"value_or_null"`
}

func (x *NullableBool) Reset() {
	*x = NullableBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nullable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableBool) ProtoMessage() {}

func (x *NullableBool) ProtoReflect() protoreflect.Message {
	mi := &file_nullable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableBool.ProtoReflect.Descriptor instead.
func (*NullableBool) Descriptor() ([]byte, []int) {
	return file_nullable_proto_rawDescGZIP(), []int{1}
}

func (m *NullableBool) GetValueOrNull() isNullableBool_ValueOrNull {
	if m != nil {
		return m.ValueOrNull
	}
	return nil
}

func (x *NullableBool) GetBoolValue() bool {
	if x, ok := x.GetValueOrNull().(*NullableBool_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *NullableBool) GetNullValue() structpb.NullValue {
	if x, ok := x.GetValueOrNull().(*NullableBool_NullValue); ok {
		return x.NullValue
	}
	return structpb.NullValue(0)
}

type isNullableBool_ValueOrNull interface {
	isNullableBool_ValueOrNull()
}

type NullableBool_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type NullableBool_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,2,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

func (*NullableBool_BoolValue) isNullableBool_ValueOrNull() {}

func (*NullableBool_NullValue) isNullableBool_ValueOrNull() {}

type NullableString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ValueOrNull:
	//
	//	*NullableString_StringValue
	//	*NullableString_NullValue
	ValueOrNull isNullableString_ValueOrNull `protobuf_oneof:"value_or_null"`
}

func (x *NullableString) Reset() {
	*x = NullableString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nullable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableString) ProtoMessage() {}

func (x *NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_nullable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableString.ProtoReflect.Descriptor instead.
func (*NullableString) Descriptor() ([]byte, []int) {
	return file_nullable_proto_rawDescGZIP(), []int{2}
}

func (m *NullableString) GetValueOrNull() isNullableString_ValueOrNull {
	if m != nil {
		return m.ValueOrNull
	}
	return nil
}

func (x *NullableString) GetStringValue() string {
	if x, ok := x.GetValueOrNull().(*NullableString_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *NullableString) GetNullValue() structpb.NullValue {
	if x, ok := x.GetValueOrNull().(*NullableString_NullValue); ok {
		return x.NullValue
	}
	return structpb.NullValue(0)
}

type isNullableString_ValueOrNull interface {
	isNullableString_ValueOrNull()
}

type NullableString_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type NullableString_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,2,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

func (*NullableString_StringValue) isNullableString_ValueOrNull() {}

func (*NullableString_NullValue) isNullableString_ValueOrNull() {}

var File_nullable_proto protoreflect.FileDescriptor

var file_nullable_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x2f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x0c, 0x4e, 0x75,
	0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x09, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x6e, 0x75, 0x6c, 0x6c, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4e, 0x75,
	0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x75, 0x6c, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6f, 0x72,
	0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x22, 0x7d, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x6e, 0x75, 0x6c, 0x6c, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4e, 0x75, 0x6c,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x75, 0x6c, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6f, 0x72, 0x5f,
	0x6e, 0x75, 0x6c, 0x6c, 0x22, 0x83, 0x01, 0x0a, 0x0e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x0a,
	0x6e, 0x75, 0x6c, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09,
	0x6e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x5f, 0x6f, 0x72, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x74, 0x65, 0x63, 0x6c, 0x61,
	0x79, 0x2f, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2d, 0x70, 0x62, 0x3b, 0x6e, 0x75,
	0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nullable_proto_rawDescOnce sync.Once
	file_nullable_proto_rawDescData = file_nullable_proto_rawDesc
)

func file_nullable_proto_rawDescGZIP() []byte {
	file_nullable_proto_rawDescOnce.Do(func() {
		file_nullable_proto_rawDescData = protoimpl.X.CompressGZIP(file_nullable_proto_rawDescData)
	})
	return file_nullable_proto_rawDescData
}

var file_nullable_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nullable_proto_goTypes = []any{
	(*NullableDate)(nil),          // 0: nullable.NullableDate
	(*NullableBool)(nil),          // 1: nullable.NullableBool
	(*NullableString)(nil),        // 2: nullable.NullableString
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(structpb.NullValue)(0),       // 4: google.protobuf.NullValue
}
var file_nullable_proto_depIdxs = []int32{
	3, // 0: nullable.NullableDate.date_value:type_name -> google.protobuf.Timestamp
	4, // 1: nullable.NullableDate.null_value:type_name -> google.protobuf.NullValue
	4, // 2: nullable.NullableBool.null_value:type_name -> google.protobuf.NullValue
	4, // 3: nullable.NullableString.null_value:type_name -> google.protobuf.NullValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nullable_proto_init() }
func file_nullable_proto_init() {
	if File_nullable_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nullable_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NullableDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nullable_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NullableBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nullable_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NullableString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nullable_proto_msgTypes[0].OneofWrappers = []any{
		(*NullableDate_DateValue)(nil),
		(*NullableDate_NullValue)(nil),
	}
	file_nullable_proto_msgTypes[1].OneofWrappers = []any{
		(*NullableBool_BoolValue)(nil),
		(*NullableBool_NullValue)(nil),
	}
	file_nullable_proto_msgTypes[2].OneofWrappers = []any{
		(*NullableString_StringValue)(nil),
		(*NullableString_NullValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nullable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nullable_proto_goTypes,
		DependencyIndexes: file_nullable_proto_depIdxs,
		MessageInfos:      file_nullable_proto_msgTypes,
	}.Build()
	File_nullable_proto = out.File
	file_nullable_proto_rawDesc = nil
	file_nullable_proto_goTypes = nil
	file_nullable_proto_depIdxs = nil
}
